### ISSUE TITLE
Can't install with nix

### ISSUE THREAD

**Issue by jwnki** [eikek/chee#17]
Hi, I realize you are not doing much with this, but maybe you'll find some time to help me? It would be great. I really like the software!

The issue is: I am unable to install it using nix. I tried both `nix-env` command you suggest and downloading the source and running `nix-build` within the project dir. Both end up in an `sbt` error:

```
Error: Could not retrieve sbt 0.13.13
builder for '/nix/store/a9h2rax4ccx3lwnnmbqkjr52a2ks05jg-chee-0.3.0.drv' failed with exit code 1
error: build of '/nix/store/a9h2rax4ccx3lwnnmbqkjr52a2ks05jg-chee-0.3.0.drv' failed

```
(stack trace: [https://pastebin.com/GAVAcP2B](https://pastebin.com/GAVAcP2B))
Most probably caused by:   
`You probably access the destination server through a proxy server that is not well configured.`

What I find weird is that when I downloaded the source, installed jdk and sbt, I was able to build the program by issuing: `sbt make-zip` as you describe. This makes me think that maybe the issue is with some variables being set by `nix` but I was unable to track down the specifics. 

EDIT:
Not sure how useful this is but I realized that when issuing `sbt make-zip` it downloads from: `downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/jars/sbt.jar` while in the error case it doesn't use the typesafe repo.

**Comment by eikek** [comment]
Hello @WhosCounting, sorry for this! You're right, I'm not doing much here anymore. Reason is mainly that it is doing what I want :) But this also means that some things are outdated. The nix recipe is one such thing. Back then I tried to compile the software from within the nix build. But due to too many problems with this approach, I'm now just installing from a pre-build zip file. I'm now using this nix derivation:

``` nix
{ stdenv, fetchurl, unzip, jre8  }:

with stdenv.lib;

stdenv.mkDerivation rec {
  version = "0.3.0";
  name = "chee-${version}";

  src = fetchurl {
    url = "https://github.com/eikek/chee/releases/download/release%2F${version}/chee-${version}.zip";
    sha256 = "1g8dd0dlzdhhr4jiiz3vb62pikwl48rksppzg9z51d6qrc044vmi";
  };

  unpackPhase = ''
    ${unzip}/bin/unzip $src
  '';

  installPhase = ''
    mkdir -p $out/{bin,program}
    cp -r chee-${version}/* $out/program
    sed -i 's,^java,${jre8}/bin/java,g' $out/program/chee
    ln -s $out/program/chee $out/bin/chee
    chmod 755 $out/program/chee
  '';

  meta = {
    description = "Chee is a command line tool for managing photos.";
    homepage = https://github.com/eikek/chee;
    license = licenses.gpl3;
  };
}
```

**Comment by jwnki** [comment]
Oh, don't be sorry! I meant it as a polite way of asking for help :) 
Thanks for your derivation, this works for me (for possible future readers: I had to replace the first line with: `with import <nixpkgs>{};`). And thanks one more time for sharing chee, I like it a lot.

**Comment by eikek** [comment]
You are welcome; and thanks for the kind words!
